# Generated by Django 3.2.9 on 2022-03-03 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20220303_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='extra_column',
        ),
    ]
